package cities

import "time"

type City struct {
	Name                           string    `json:"name"`
	Timestamp                      time.Time `json:"timestamp"`
	Temperature                    string    `json:"temperature"`
	Humidity                       string    `json:"humidity"`
	Pressure                       string    `json:"pressure"`
	Description                    string    `json:"description"`
	Co                             string    `json:"co"`
	No2                            string    `json:"no2"`
	O3                             string    `json:"o3"`
	Pm10                           string    `json:"pm10"`
	Pm25                           string    `json:"pm25"`
	So2                            string    `json:"so2"`
	CPI                            string    `json:"cpi"`
	GDPPerCapita                   string    `json:"gdp_per_capita"`
	Exports                        string    `json:"exports"`
	Imports                        string    `json:"imports"`
	Unemployment                   string    `json:"unemployment"`
	IndividualsUsingInternet       string    `json:"internet_users"`
	TaxRevenue                     string    `json:"tax_revenue"`
	LifeExpectancy                 string    `json:"life_expectancy"`
	MortalityRateUnder5            string    `json:"infant_mortality"`
	GovtExpenditureEducation       string    `json:"spending_on_education"`
	CO2Emissions                   string    `json:"co2_emissions"`
	LiteracyRate                   string    `json:"literacy_rate"`
	CurrentHealthExpenditure       string    `json:"spending_on_health"`
	PovertyHeadcount               string    `json:"poverty"`
	HealthExpenditurePerCapita     string    `json:"health_spending_per_capita"`
	PairOfJeans                    string    `json:"pair_of_jeans"`
	Apartment1BedroomOutsideCentre string    `json:"rent_1_bedroom_apartment_non_central"`
	Apartment1BedroomCityCentre    string    `json:"rent_1_bedroom_apartment_central"`
	Apples                         string    `json:"1kg_of_apples"`
	MonthlyNetSalary               string    `json:"monthly_net_salary"`
	Banana                         string    `json:"1kg_of_bananas"`
	BasicUtilities                 string    `json:"basic_utilities_for_85m2_apartment"`
	BeefRound                      string    `json:"1kg_of_beef_round"`
	BottleOfWine                   string    `json:"bottle_of_wine"`
	Cappuccino                     string    `json:"cappuccino"`
	ChickenFillets                 string    `json:"1kg_of_chicken_fillets"`
	Cigarettes                     string    `json:"pack_of_cigarettes"`
	DomesticBeerBottle             string    `json:"bottle_of_beer"`
	Eggs                           string    `json:"12_eggs"`
	Gasoline                       string    `json:"1l_of_gasoline"`
	InternationalPrimarySchool     string    `json:"primary_school_yearly"`
	Internet                       string    `json:"internet_60_mbps_or_more"`
	Bread                          string    `json:"1kg_of_bread"`
	LocalCheese                    string    `json:"1kg_of_cheese"`
	McMeal                         string    `json:"meal_at_mcdonalds_or_similar"`
	MealFor2                       string    `json:"meal_for_2_in_mid_range_restaurant"`
	Milk                           string    `json:"1l_of_milk"`
	MobilePlan                     string    `json:"mobile_plan_monthly"`
	MonthlyPass                    string    `json:"monthly_pass"`
	MortgageInterestRate           string    `json:"mortgage_interest_rate"`
	OneWayTicket                   string    `json:"local_one_way_ticket"`
	Oranges                        string    `json:"1kg_of_oranges"`
	Potato                         string    `json:"1kg_of_potatoes"`
	Preschool                      string    `json:"kindergarten_monthly"`
	Taxi1Mile                      string    `json:"taxi_1_km"`
	Tomato                         string    `json:"1kg_of_tomatoes"`
	WaterBottle                    string    `json:"1.5l_water_bottle"`
	Motto                          string    `json:"motto"`
	PopulationTotal                string    `json:"population"`
	AreaTotal                      string    `json:"area"`
	Elevation                      string    `json:"elevation"`
	Timezone                       string    `json:"timezone"`
	PopulationDensity              string    `json:"density"`
}
